export const LOAD_PEOPLE_LIST = 'LOAD_PEOPLE_LIST';
export const LOAD_PEOPLE_LIST_ERROR = 'LOAD_PEOPLE_LIST_ERROR';
export const LOAD_CHAT_LIST = 'LOAD_CHAT_LIST';
export const LOAD_CHAT_LIST_ERROR = 'LOAD_CHAT_LIST_ERROR';
export const LOAD_COORDINATE = 'LOAD_COORDINATE';
export const LOAD_COORDINATE_ERROR = 'LOAD_COORDINATE_ERROR';